version: '3'

services:
  app:
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - host.docker.internal:172.17.0.1
    # depends_on:
    #   - db
  # db:
  #   build: ./.docker/mysql
  #   restart: always
  #   tty: true
  #   volumes: 
  #     - ./.docker/mysql?;var/lib/mysql
  #   environment:
  #     - MYSQL_DATABASE=fin
  #     - MYSQL_ROOT_PASSWORD=root