version: '3'

services:
  app:
    build: 
      context: ./nest/
    entrypoint: ./entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - host.docker.internal:172.17.0.1
    depends_on:
      - keycloak
      - front

  front:
    build:
      context: ./front/vue-login/

  keycloak: 
    image: jboss/keycloak:15.0.0
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - 8080:8080